apiVersion: v1
kind: Service
metadata:
  name: "service-2048-demo"
  namespace: "2048-game-demo"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "2048"
